create table if not exists public.customer_reviews (
 id bigint generated by default as identity primary key,
 customer_name text not null check (char_length(trim(customer_name)) between 1 and 80),
 project_type text not null check (char_length(trim(project_type)) between 1 and 80),
 rating integer not null check (rating between 1 and 5),
 comment text not null check (char_length(trim(comment)) between 1 and 1500),
 project_photo_url text null,
 marketing_consent boolean not null default false,
 status text not null default 'pending' check (status in ('pending','approved','rejected')),
 created_at timestamptz not null default now()
);
alter table public.customer_reviews enable row level security;
revoke all on public.customer_reviews from anon, authenticated;
grant select (id,customer_name,project_type,rating,comment,project_photo_url,created_at) on public.customer_reviews to anon,authenticated;
grant insert (customer_name,project_type,rating,comment,project_photo_url,marketing_consent) on public.customer_reviews to anon,authenticated;
drop policy if exists "Anyone can read approved customer reviews" on public.customer_reviews;
create policy "Anyone can read approved customer reviews" on public.customer_reviews for select to anon,authenticated using (status='approved');
drop policy if exists "Anyone can submit pending customer reviews" on public.customer_reviews;
create policy "Anyone can submit pending customer reviews" on public.customer_reviews for insert to anon,authenticated with check (status='pending');
grant usage,select on sequence public.customer_reviews_id_seq to anon,authenticated;
