-- Saujana Sejati Ent: Web Push subscriptions
-- Run this SQL in Supabase SQL Editor before deploying the Edge Function.

create table if not exists public.push_subscriptions (
  id bigint generated by default as identity primary key,
  endpoint text not null unique,
  subscription jsonb not null,
  recipient text not null check (recipient in ('hairi', 'amirul')),
  created_at timestamptz not null default now(),
  updated_at timestamptz not null default now()
);

create table if not exists public.booking_push_log (
  booking_id uuid primary key,
  sent_at timestamptz not null default now(),
  result jsonb not null default '{}'::jsonb
);

alter table public.push_subscriptions enable row level security;
alter table public.booking_push_log enable row level security;

-- No anon/authenticated policies are created intentionally.
-- Only the Edge Function using SUPABASE_SERVICE_ROLE_KEY should access these tables.
revoke all on public.push_subscriptions from anon, authenticated;
revoke all on public.booking_push_log from anon, authenticated;
grant all on public.push_subscriptions to service_role;
grant all on public.booking_push_log to service_role;
